services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./src/shared_db_models/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped

  app:
    build: .
    command: python ./src/main.py
    volumes:
      - .:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                  #- utility # nvidia-smi
                  #- compute # CUDA
                  #- video   # NVDEC/NVENC/NVCUVID
